# For helping to test boot_metrics
sens = [0.5, 0.8, 0.85, 0.9, 0.95, 0.99]
global_only = False
interp_step = 0.01
prob_min = 0.2
B = 1
boot_method = 'percentile'
M = 10
max_iter = 10
impute_y = False
random_state = 42
n_noci = 5
parallel = False
save = False
repl_ypred_nan = False
stratified_boot = False
models_recal = ['nottingham-lr', 'nottingham-cox']
return_boot_samples = False
fit_ebm = False
fit_spline = True
nchunks = 1
raw_rocpr = False